data_path : 'data/Beijing/'
data:
  batch_size: 64
  num_input_station: 20
  nan_station: 
    - 植物园
    - 榆垡
  input_features:
    - AQI
    - PM10
    - PM2.5
    - CO
    - NO2
    - O3
    - SO2
    - wind
    - temp
    - prec
    - shum
    - srad
    - pres
    - Mean
    - lrad
  target_features:
    - PM2.5

n_in : 9
n_out : 1
n_timestep : 1

lr : 0.0001
num_station: 33

dropout: 0.3
batch_size: 32
epochs: 100
lookup_size: 1

conv:
  in_channels1: 1
  out_channels1: 64
  kernel_size1: 5

  in_channels2: 64
  out_channels2: 32
  kernel_size2: 3

  in_channels3: 32
  out_channels3: 16
  kernel_size3: 1

  # in_features_fc:
  out_features_fc: 24
  kernel_size_maxpool: 3
  stride_maxpool: 1 
  padding_maxpool: 1

bilstm:
  # input_size: 3
  hidden_size: 128
  num_layers: 1

fusion:
  # in_features_fs:
  out_features_fs: 64
  
  
  
